---
# Install the Railgun Relayer

- name: Install prerequisite packages
  package:
    name:
      - acl
      - python3-pip
    state: present

- name: Install prerequisite python packages
  pip:
    name: docker
    executable: pip3

# Gather IP facts from ipify.org
- name: Get node's public IP
  community.general.ipify_facts:

- name: Create a Railgun system user
  ansible.builtin.user:
    name: railgun
    comment: Railgun Relayer
    shell: /bin/bash
    groups: docker
    append: true

- name: Check out the Railgun repository
  ansible.builtin.git:
    repo: git@github.com:Railgun-Community/relayer.git
    version: master
    dest: /home/railgun/relayer
  become: true
  become_user: railgun

- name: Initialise Docker Swarm if needed
  community.docker.docker_swarm:
    state: present

- name: Check what secrets exist already
  command:
    cmd: "docker secret ls"
  register: docker_secrets

- name: Check for existence of Docker .env file
  stat:
    path: "/home/railgun/relayer/docker/.env"
  register: docker_env

- name: Fetch Docker .env file
  fetch:
    src: "/home/railgun/relayer/docker/.env"
    dest: /tmp/rg.env
    flat: true
  when: docker_env.stat.exists

- name: Read nodekey
  set_fact:
    railgun_nodekey: "{{ lookup('ini', 'nodekey', type='properties', file='/tmp/rg.env') }}"
  when: docker_env.stat.exists

- name: Generate nodekey secret if needed
  shell:
    cmd: "./scripts/nodekey.sh"
    chdir: "/home/railgun/relayer"
  when: railgun_nodekey is not defined or railgun_nodekey|length == 0
  register: railgun_nodekey_gen

- name: Store generated nodekey as a fact
  set_fact:
    railgun_nodekey: "{{ railgun_nodekey_gen.stdout }}"
  when: railgun_nodekey_gen.stdout is defined

- name: Create Railgun facts
  set_fact:
    railgun_public_ip: "{{ ipify_public_ip }}"

- name: Generate and store DB_ENCRYPTION_KEY secret if needed
  shell:
    cmd: "./scripts/nodekey.sh | docker secret create DB_ENCRYPTION_KEY -"
    chdir: "/home/railgun/relayer"
  when: '"DB_ENCRYPTION_KEY" not in docker_secrets.stdout'

- name: Store NODEKEY secret if needed
  shell:
    cmd: "echo {{ railgun_nodekey }} | docker secret create NODEKEY -"
    chdir: "/home/railgun/relayer"
  when: '"NODEKEY" not in docker_secrets.stdout'

- name: Register MNEMONIC secret if needed
  community.docker.docker_secret:
    name: MNEMONIC
    data: "{{ railgun_seed }}"
    state: present
  when: '"MNEMONIC" not in docker_secrets.stdout'

- name: Create docker .env file
  template:
    src: .env.j2
    dest: /home/railgun/relayer/docker/.env
    owner: railgun
    group: railgun
    mode: 0600

- name: Create a directory to hold appdata
  file:
    path: /home/railgun/relayer/docker/appdata
    state: directory
    owner: railgun
    group: railgun
    mode: 0700

- name: Create a directory to hold Swag configuration and data
  file:
    path: /home/railgun/relayer/docker/appdata/swag
    state: directory
    owner: railgun
    group: railgun
    mode: 0700

- name: Create MY-CONFIG.ts file
  template:
    src: MY-CONFIG.ts.j2
    dest: /home/railgun/relayer/src/MY-CONFIG.ts
    owner: railgun
    group: railgun
    mode: 0644

- name: Build Docker images
  command:
    cmd: "./docker/build.sh"
    chdir: "/home/railgun/relayer"

- name: Run Docker images
  command:
    cmd: "./docker/run.sh"
    chdir: "/home/railgun/relayer"
