name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello World
        run: make

  fail-report:
    if: ${{ failure() }}
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram message with fail report
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CI_TELEGRAM_TO }}
          token: ${{ secrets.CI_TELEGRAM_TOKEN }}
          format: markdown
          message: |
            ❌ **${{ github.repository }}** - Workflow "${{ github.workflow }}"
            Commit "[${{ github.event.commits[0].message }}](https://github.com/${{ github.repository }}/commit/${{github.sha}})" 
