name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello World
        run: make

  ci-report:
    if: ${{ failure() }}
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Needs context
        env:
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
        run: |
          echo "$NEEDS_CONTEXT"

      - name: Send Telegram message with report
        uses: appleboy/telegram-action@master
        env:
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
        with:
          to: ${{ secrets.CI_TELEGRAM_TO }}
          token: ${{ secrets.CI_TELEGRAM_TOKEN }}
          message: |
            **${{ needs.build.result }}** in **${{ github.repository }}**: Workflow ID ${{ github.workflow }}: ${{ toJSON(needs) }}